---
title: "Getting set up with GitHub in RStudio"
author: "Stephanie Lax and Adam Taylor"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

19/08/2025:

1. Adam created `UoN-RECORDER/GitPractice` repo
2. Steph logged into GitHub 
3. Steph created a new fork of the GitPractice repo (**fork** = copy of repo where changes can be made without affecting the original. Saved to personal account by default)

26/08/2025:

1. Adam had advised to clone the repo directly and to make changes and branch within RStudio. Otherwise, the GitHub website version can diverge from the local version if changes are not immediately pulled to the local copy.
2. Steph cloned the repo within RStudio using `New Project > Version Control > Git` using the main URL. Please note, the main URL is different to the webpage URL (the latter contains `/tree/`). The main URL is found by clicking the green code button on the repo.
3. Steph created a new `Steph` branch in RStudio via the purple flowchart icon in the top right of the Git window. This process automatically switched from the main to the new branch.
4. Steph made edits to `Getting_Set_up.Rmd`, committed, and then pushed the changes.